[versions]

# AGP的版本
agp = "8.13.1"

# AndroidX 稳定版本（组件依赖时使用）
androidxAppcompatStable = "1.6.1"
activityStable = "1.7.2"
androidxActivityKtxStable = "1.7.2"
kotlinStable = "1.7.21"

# AndroidX 较新版本（App依赖时使用）
androidxAppcompat = "1.7.1"
androidxActivityKtx = "1.11.0"
androidxConstraintlayout = "2.2.1"
androidxCore = "1.17.0"
cardview = "1.0.0"
material = "1.13.0"

# Kotlin
kotlin = "2.2.21"

# Gradle 插件
xeonBuildManager = "0.0.7"
vanniktechPublish = "0.35.0"

[libraries]

# 稳定版本（组件使用）
androidx-appcompat-stable = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompatStable" }
androidx-activity-stable = { group = "androidx.activity", name = "activity", version.ref = "activityStable" }
androidx-activity-ktx-stable = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtxStable" }
kotlin-bom-stable = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinStable" }

# 较新版本（App使用）
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
xeonyu-application = { id = "com.xeonyu.plugin.application", version.ref = "xeonBuildManager" }
xeonyu-library = { id = "com.xeonyu.plugin.library", version.ref = "xeonBuildManager" }
